### ISSUE TITLE
inconsistent round borders/corners

### ISSUE THREAD

**Issue by Delected** [yshui/picom#683]
### Platform
Void Linux amd64/x64 Intel Pentium CPU 

### GPU, drivers, and screen setup
xf86-video-intel-2.99.917.20210115_1

my glxinfo -B:

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Mobile Intel® GM45 Express Chipset (CTG) (0x2a42)
    Version: 21.2.1
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Mobile Intel® GM45 Express Chipset (CTG)
OpenGL version string: 2.1 Mesa 21.2.1
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 21.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

### Environment
dwm

### picom diagnostics
```
**Version:** vgit-ee7d9

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: None

### Drivers (inaccurate):

Intel

### Backend: glx

[ 09/03/2021 14:15:08.042 glx_init ERROR ] Failed to get GLX context.
 Cannot initialize this backend
```

### Configuration
any configuration where i add round borders and corners generates this error for me.

### Expected behavior
I expect the glx and xrender backends to generate the same borders and corners as long as I am not using the experimental backends option. 

### Current Behavior
when running picom from terminal using the glx backend with rounded corners, i am getting an error `[ 09/03/2021 14:20:26.007 glx_init_rounded_corners ERROR ] GLX error at line 567: GL_INVALID_ENUM`. If i remove the rounded corners from my config, the error goes away. Note that picom still runs fine even with the error (see video below). I tried using a more sane xrender backend, and there were no glx errors (obviously) in console. the round corners also look much smoother using xrender. the biggest inconsistency is that using xrender the corners of my windows are still square, while my borders stay rounded. this is very hard to put in words so please see the video below (you might need to zoom a little to see the difference.)

[youtube video, sorry i could not directly add it to github since it's an ogv file](https://youtu.be/uj6hdNIYm6c)

the weirdest part is that even using glx, the corners are still inconsistent.  [A user on Reddit](https://www.reddit.com/r/unixporn/comments/pgf306/dwm_uhm_need_title/?sort=new) (also @edencreeper on github) is having the same issue, even on the same display. If you take a look at the linked post, some of the window corners are rounded while others are not. this is very odd... I invite anyone else to please expand on this by adding their experiences.

lastly, it is worth noting that this issue persists on ibhawgan's fork of picom too. I just wanted to make sure in case his pr was not fully merged here yet

**Comment by Delected** [comment]
ok wait i just realized how horrible the video recording is.. maybe not such a great idea to video record on an ancient laptop

**Comment by Delected** [comment]
yeah, i wonder if any attention will be brought to this

>

**Comment by MaybeAnonymous** [comment]
i have the exact same problem

**Comment by JohnBish** [comment]
Same here

**Comment by yshui** [comment]
The xrender backend doesn't have the ability to draw rounded borders, sorry.

For the inconsistencies in the glx backend, looks like the border width isn't detected correctly. Can you:
1. try the experimental backend
2. run `xwininfo` on a window that's not rendered correctly. in your case, an unfocused window.

**Comment by MaybeAnonymous** [comment]
i have switched to bspwm and no longer have the problem

**Comment by gnaqvi** [comment]
Using bspwm 0.9.10-1 and having the same issue. When window loses focus then _inner_ corners are rounded correctly.

**Comment by gnaqvi** [comment]
Setting `use-damage` to false fixes the flickering and artifacts for me.

**Comment by Danila-hub** [comment]
> Setting `use-damage` to false fixes the flickering and artifacts for me.

This method really be useful, thanks!!!

**Comment by alexcoder04** [comment]
I am also experiencing the same problem on basically every window on i3wm, `use-damage` doesn't help

**Comment by welcoMattic** [comment]
I have the same bug using Manjaro i3 + picom.
- Using `use-damage = true` doesn't change anything
- Using either `glx` or `xrender` doesn't change anything

**Comment by Vishvamitra** [comment]
Hello everyone! I'm noticing that nobody has written a post for almost one month but, since I tried picom for the first time today, I'd wish to report the same issue which @Delected pointed out in his first post. I've been experiencing this inconsistency between border and window radius since when I first enabled corner-radius in picom conf today.

Here are a couple of informations on my sistem:
* Debian 11 bookworm
* picom version is the one I installed from Debian repositories
* Graphics: Intel HD Graphics i915 driver (no dedicated graphic card)
![2022-07-17-204958_83x47_scrot](https://user-images.githubusercontent.com/40338178/179421035-e5a8b522-9503-4e80-baa3-89cbebaa2350.png)

**Comment by yshui** [comment]
This should've been fixed in experimental backends already.

**Comment by Vishvamitra** [comment]
@yshui  Unfortunately, the issue still persists even though both `glx` and `--experimental-backends` options are enabled.

![2022-07-18-111331_63x47_scrot](https://user-images.githubusercontent.com/40338178/179481063-7f065a2f-3bd9-4cd1-b1c9-6ef86418df9e.png)

I was able to get rid of the screen tearing through  the `glx` and the `vysnc = true` options though, so I'm pretty happy with my setup. I guess I'll disable rounded corners and keep an eye on further developments. Thank you for replying!

**Comment by yshui** [comment]
@Vishvamitra Are you using the latest git build?

**Comment by yshui** [comment]
@Vishvamitra If you have time can you use apitrace to record a trace of picom?

**Comment by Vishvamitra** [comment]
@yshui Yes, sure! It's the first time I'm using apitrace though: what command am I supposed to type?

**Comment by Vishvamitra** [comment]
@yshui I  have followed your instructions and I've generated three `picom.trace` files: I'm uploading the third one, since I ran this tracing on a completely blank workspace and it's the smallest file. I'll upload a .zip file.

[picom.trace.zip](https://github.com/yshui/picom/files/9131736/picom.trace.zip)

**Comment by yshui** [comment]
@Vishvamitra  you didn't enable round corner in your trace?

**Comment by yshui** [comment]
@Vishvamitra Don't worry about it! I need to enable rounded corner while capturing the trace, so the trace can help me understand what is happening when the corner is rendered.

**Comment by Vishvamitra** [comment]
Sure! I'll run another test quickly and post the zip here.

**Comment by yshui** [comment]
@Vishvamitra you weren't using `--experimental-backends`

**Comment by Vishvamitra** [comment]
Sorry, I didn't know I was supposed to, since that flag doesn't give me a different result.
If I want to run a new test, should I run the following command `apitrace trace picom --experimental-backends --log-level=trace`?

**Comment by yshui** [comment]
@Vishvamitra No worries! Thank you for taking your time to repeat this so many times.

May I ask what WM are you using? What is the `xprop` and `xwininfo` output for your terminal window?

**Comment by yshui** [comment]
maybe i3 treated mpv differently, i don't know. 

If you want this fixed you should prod the i3 devs.

**Comment by Vishvamitra** [comment]
> If you want this fixed you should prod the i3 devs.

@yshui I'll check their github page and see if any issue about this problem has been opened yet.
Even though my knowledge about this topic is quite limited, I can't keep wondering if hardware acceleration should be considered, because mpv is using hardware acceleration and it renders the corners properly.

**Comment by yshui** [comment]
@Vishvamitra 
> if any issue about this problem has been opened yet.

I linked the issue in my comment above.

**Comment by Vishvamitra** [comment]
Yes, I've just noticed. Thank you!

**Comment by ZyxerZyxani** [comment]
> I solved this by
> 
> ```
> backend = "glx";
> 
> use-damage = false;
> ```

This solved it for me. Thanks so much! 
The issue for me was somewhat different than described here tho'. Firefox had rounded corners as well as dwm status bar. However, kitty had no rounded corners and neither did st. I found the solution before I had time to do more testing, but it seems no terminal would get the rounded corners. 

I am on dwm, linux void.

**Comment by ciceropaulino** [comment]
> I solved this by
> 
> ```
> backend = "glx";
> 
> use-damage = false;
> ```

This works for me in Debian 12
